# 基础镜像
#FROM openjdk:17-oracle
#FROM  openjdk-chinese:8-jre
FROM  openjdk:8-jre
# author
MAINTAINER staitech

# 挂载目录
VOLUME /home/staitech
# 创建目录
RUN mkdir -p /home/staitech

# 指定路径
WORKDIR /home/staitech
# 复制jar文件到路径
COPY ./jar/staitech-modules-fr.jar /home/staitech/staitech-modules-fr.jar
COPY jmx_prometheus_javaagent-0.16.1.jar jmx_prometheus_javaagent.jar
COPY jmx_config.yaml jmx_config.yaml

# 启动系统服务
ENTRYPOINT ["sh","-c","java $JAVA_OPTS -javaagent:/home/staitech/jmx_prometheus_javaagent.jar=1234:/home/staitech/jmx_config.yaml -jar staitech-modules-fr.jar"]