-- 初始化脏器标签（59条）
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'00','Others','其他','AA','rgb(0, 0, 0)','#000000',1,1,1,0,0);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'01','Adrenal glands','肾上腺','AG','rgb(255, 0, 0)','#FF0000',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'05','Pancreas','胰腺','PA','rgb(0, 0, 255)','#0000FF',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'06','Pituitary','垂体','PI','rgb(255, 255, 0)','#FFFF00',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'07','Thyroid gland','甲状腺','TG','rgb(255, 0, 255)','#FF00FF',1,1,1,0,0);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'08','Parathyroid','甲状旁腺','PD','rgb(0, 255, 255)','#00FFFF',1,1,1,0,0);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'09','Salivary glands, parotid','唾液腺，腮腺','PG','rgb(0, 114, 189)','#0072BD',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'0A','Salivary glands, sublingual','唾液腺，舌下腺','SD','rgb(217, 83, 25)','#D95319',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'0B','Salivary glands, mandibular','唾液腺，颌下腺','MD','rgb(237, 177, 32)','#EDB120',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'0D','Tongue','舌','TO','rgb(126, 47, 142)','#7E2F8E',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'0E','Larynx','喉','LA','rgb(119, 172, 48)','#77AC30',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'0F','Esophagus','食管','ES','rgb(77, 190, 238)','#4DBEEE',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'10','Stomach (glandular and non-glandular)','胃（腺胃和非腺胃）','SM','rgb(162, 20, 47)','#A2142F',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'11','Gall bladder','胆囊','GR','rgb(255, 255, 0)','#FFFF00',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'12','Liver','肝脏','LI','rgb(0, 128, 0)','#008000',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'14','Cecum','肠，盲肠','CE','rgb(0, 0, 128)','#000080',1,1,1,0,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'15','Colon','肠，结肠','CO','rgb(128, 128, 0)','#808000',1,1,1,0,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'16','Rectum','肠，直肠','RE','rgb(128, 0, 128)','#800080',1,1,1,0,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'17','Ileum (with Peyer’s Patch)','肠，回肠（含派氏结）','IL','rgb(0, 128, 128)','#008080',1,1,1,0,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'18','Jejunum','肠，空肠','JE','rgb(128, 0, 255)','#8000FF',1,1,1,0,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'19','Duodenum','肠，十二指肠','DU','rgb(0, 128, 255)','#0080FF',1,1,1,0,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'1B','Kidneys','肾脏','KI','rgb(255, 128, 128)','#FF8080',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'1E','Urinary bladder','膀胱','UB','rgb(128, 128, 255)','#8080FF',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'24','Ovaries','卵巢','OS','rgb(200, 200, 255)','#C8C8FF',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'25','Oviduct','输卵管','OT','rgb(255, 255, 200)','#FFFFC8',1,1,1,1,0);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'26','Uterus','子宫','UT','rgb(255, 200, 255)','#FFC8FF',1,1,1,1,0);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'27','Cervix','子宫颈','CX','rgb(200, 255, 255)','#C8FFFF',1,1,1,1,0);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'28','Vagina','阴道','VA','rgb(255, 0, 0)','#FF0000',1,1,1,1,0);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'2C','Prostate','前列腺','PR','rgb(0, 0, 255)','#0000FF',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'2D','Seminal vesicles','精囊腺','SV','rgb(255, 255, 0)','#FFFF00',1,1,1,1,0);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'2E','Testis','睾丸','TE','rgb(255, 0, 255)','#FF00FF',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'2F','Epididymides','附睾','EP','rgb(0, 255, 255)','#00FFFF',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'32','Brain','大脑','BR','rgb(0, 114, 189)','#0072BD',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'39','Spinal cord (cervical, thoracic, lumbar)','脊髓（颈、胸、腰）','SC','rgb(217, 83, 25)','#D95319',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'3D','Brain stem','脑干','BS','rgb(237, 177, 32)','#EDB120',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'3E','Cerebellum','小脑','CM','rgb(126, 47, 142)','#7E2F8E',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'3F','Optic nerve','视神经','OE','rgb(119, 172, 48)','#77AC30',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'40','Nerve, sciatic','神经，坐骨','SE','rgb(77, 190, 238)','#4DBEEE',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'44','Thymus','胸腺','TH','rgb(162, 20, 47)','#A2142F',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'45','Spleen','脾脏','SP','rgb(0, 128, 0)','#008000',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'46','Lymph node, mesenteric','淋巴结，肠系膜','MN','rgb(0, 0, 128)','#000080',1,1,1,0,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'47','Lymph node, inguinal','淋巴结，腹股沟','IE','rgb(128, 128, 0)','#808000',1,1,1,0,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'48','Lymph node, mandibular','淋巴结，下颌','ML','rgb(128, 0, 128)','#800080',1,1,1,0,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'4B','Lymph node','淋巴结','LN','rgb(255, 128, 128)','#FF8080',1,1,1,1,0);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'4C','Lung with bronchi','肺（含支气管）','LU','rgb(0, 128, 128)','#008080',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'4D','Trachea','气管','TR','rgb(255, 128, 0)','#FF8000',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'4E','Bone with bone marrow, sternum','骨和骨髓，胸骨','SN','rgb(128, 0, 255)','#8000FF',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'50','Bone with bone marrow, femur','骨和骨髓，股骨','FE','rgb(145, 200, 200)','#91C8C8',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'5C','Muscle','骨骼肌','MU','rgb(255, 200, 200)','#FFC8C8',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'5D','Aorta','主动脉','AO','rgb(200, 255, 200)','#C8FFC8',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'5E','Heart','心脏','HE','rgb(200, 200, 255)','#C8C8FF',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'5F','Eye','眼睛','EY','rgb(255, 255, 200)','#FFFFC8',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'69','Lacrimal glands','泪腺','LG','rgb(255, 200, 255)','#FFC8FF',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'77','Gross lesions observed at necropsy','大体损伤','GL','rgb(128, 128, 255)','#8080FF',1,1,1,0,0);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'78','Injection site','注射局部','IS','rgb(255, 0, 128)','#FF0080',1,1,1,0,0);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'7A','Skin (close to mammary) with mammary gland','皮肤（乳腺附近）及乳腺','IN_MG','rgb(128, 128, 255)','#C8FFC8',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'7F','Thyroid glands with parathyroids','甲状腺与甲状旁腺','TG_PD','rgb(255, 0, 128)','#0080FF',1,1,1,1,1);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'82','Small Intestine','小肠','SITT','rgb(255, 0, 128)','#FF0080',1,1,1,1,0);
INSERT INTO tb_organ_tag (species_id, organ_tag_code, organ_en, organ_name, abbreviation, rgb, chromatic_value, organization_id, create_by, update_by, organ_recognition, structured_analysis) VALUES ( "3",'83','Large Intestine','大肠','LITT','rgb(255, 200, 200)','#FFC8C8',1,1,1,1,0);

-- 同步数据到脏器表
INSERT INTO tb_organ (organ_code, name, name_en, species_id, organization_id) SELECT organ_tag_code, organ_name, organ_en, species_id, organization_id FROM tb_organ_tag WHERE species_id = '3' AND organization_id = 1;

-- 插入tb_organ中不存在于tb_structure_tag_set的记录
INSERT INTO tb_structure_tag_set (structure_tag_set_name, structure_tag_set_name_en, species_id, organ_code, organization_id, create_by,update_by)
SELECT a.name, a.name_en, a.species_id, a.organ_code, a.organization_id, 1, 1
FROM tb_organ a
WHERE a.species_id = '3' AND a.organization_id = 1;

-- 结构初始化
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','4C','34C002','支气管','Bronchi','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','4C','34C003','血管','Vessel','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','4C','34C004','红细胞','Erythrocyte','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','4C','34C006','肺泡上皮细胞核','Alveolar Epithelial Cell','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','4C','34C027','间质','Mesenchyme','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','4C','34C111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','4D','34D111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','4D','34D036','黏膜上皮细胞核','Mucosal Epithelium Cell','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','4D','34D035','黏膜上皮','Mucosal Epithelium','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','50','350111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','50','35000B','关节软骨','Articular Cartilage','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','4E','34E011','红系细胞核','Erythroid Cell','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','4E','34E01A','粒系细胞','Myeloid Cell','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','4E','34E022','巨核系细胞','Megakaryocyte Cell','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','4E','34E004','红细胞','Erythrocyte','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','4E','34E012','脂肪细胞','Adipocyte','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','4E','34E111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','5C','35C111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','5C','35C027','间质','Mesenchyme','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','5C','35C02A','肌纤维','Muscle Fiber','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','5C','35C05A','肌细胞核','Myocyte Nucleus','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','1B','31B03E','髓质','Medulla','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','1B','31B03D','皮质','Cortex','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','1B','31B02D','肾小球','Glomerulus','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','1B','31B026','血管球','Glomerulus','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','1B','31B031','肾小管','Renal Tubule','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','1B','31B02E','球内细胞核','Nucleus of Glomerulus','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','1B','31B02F','球内红细胞','Erythrocyte of Glomerulus ','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','1B','31B111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','1E','31E035','黏膜上皮','Mucosa Epithelium','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','1E','31E036','黏膜上皮细胞核','Mucosal Epithelial Nucleus','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','1E','31E003','血管','Vessel','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','1E','31E111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','4B','34B054','次级滤泡','Secondary Follicle ','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','4B','34B051','生发中心','Germinal Center','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','4B','34B052','皮质+副皮质区','Cortex and Paracortex','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','4B','34B03E','髓质','Medulla','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','4B','34B111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','44','34403D','皮质','Cortex','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','44','34403E','髓质','Medulla','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','44','344004','红细胞','Erythrocyte','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','44','344111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','45','345046','红髓','Red Pulp','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','45','345047','白髓','White Pulp','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','45','345004','红细胞','Erythrocyte','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','45','345051','生发中心','Germinal Center','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','45','345048','中央动脉','Central Artery','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','45','34504A','边缘区','Marginal Zone','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','45','34505B','小梁','Trabecula','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','45','345111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','06','30607F','神经部','Pars Nervosa','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','06','306081','中间部','Pars Intermedia','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','06','306082','中间部细胞核','Pars Intermedia Nucleus','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','06','306083','远侧部','Pars Distalis','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','06','306084','远侧部细胞核','Pars Distalis Nucleus','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','06','306004','红细胞','Erythrocyte','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','06','306111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','7F','37F07C','甲状腺组织轮廓','Tissue Area of Thyroid','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','7F','37F088','甲状腺滤泡','Thyroid Follicle','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','7F','37F08A','甲状腺滤泡腔','Thyroid Follicular Lumen','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','7F','37F003','甲状腺血管','Vessel','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','7F','37F004','甲状腺红细胞','Erythrocyte','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','7F','37F089','甲状腺滤泡上皮细胞核','Thyroid Follicular Cell','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','7F','37F08F','甲状腺C细胞核','C-cell','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','7F','37F08B','甲状腺C细胞团','C-cell Cluster','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','7F','37F07D','甲状旁腺组织轮廓','Tissue Area of Parathyroid','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','7F','37F092','甲状旁腺细胞核','Chief Cell','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','01','30103D','皮质','Cortex','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','01','301056','球状带','Zona Glomerulosa','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','01','301057','束状带+网状带','Zona Fasciculate and Zona Reticularis','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','01','30103E','髓质','Medulla','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','01','301068','实质细胞核','Parenchymal Cell','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','01','301004','红细胞','Erythrocyte','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','01','301111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','05','305075','上皮细胞核','Epithelial Cell','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','05','305076','酶原颗粒','Zymogen Granule','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','05','305077','胰岛','Pancreatic Islet','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','05','305078','胰岛细胞核','Pancreatic Islet Nucleus','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','05','305027','间质','Mesenchyme','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','05','30506F','导管','Duct','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','05','305003','血管','Vessel','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','05','305111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','7A','37A06C','乳腺腺泡/导管','Acinus and Ducts','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','7A','37A061','乳腺腺泡/导管细胞核','Acinus and Ducts Nucleus','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','7A','37A07A','乳腺组织轮廓','Tissue Area of Mammary Gland','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','7A','37A111','皮肤与乳腺组织轮廓','Tissue Area of Skin and Mammary Gland','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','7A','37A096','表皮角质层','Stratum Corneum','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','7A','37A097','表皮颗粒层+棘层+基底细胞层','Nucleated Cell Layer','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','7A','37A098','毛囊','Hair Follicle','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','7A','37A099','皮脂腺','Sebaceous Glands','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','7A','37A0C3','皮肤组织轮廓','Tissue Area of Skin','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','3F','33F0BB','神经束膜内缘','Nerve Fiber Bundles','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','3F','33F0BA','神经外膜结缔组织','Connective Tissue','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','3F','33F111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','40','3400BB','神经束膜内缘','Nerve Fiber Bundles','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','40','3400BA','神经外膜结缔组织','Connective Tissue','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','40','340111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','32','33209C','脉络丛','Choroid Plexus','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','32','332003','血管','Vessel','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','32','332004','红细胞','Erythrocyte','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','32','332111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','3E','33E0A5','颗粒细胞层＋浦肯野细胞层','Granulocyte and Purkinje Cell Layer','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','3E','33E003','血管','Vessel','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','3E','33E004','红细胞','Erythrocyte','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','3E','33E111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','39','3390B3','灰质','Gray Matter','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','39','3390B2','白质','White Matter','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','39','3390B4','中央管','Central Canal','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','39','3390B5','室管膜细胞核','Ependyma Nucleus','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','39','339004','红细胞','Erythrocyte','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','39','339111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','3D','33D003','血管','Vessel','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','3D','33D004','红细胞','Erythrocyte','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','3D','33D111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','24','324004','红细胞','Erythrocyte','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','24','3240CB','卵泡','Follicle','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','24','324003','血管','Vessel','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','24','324111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','2C','32C111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','2C','32C06C','腺泡/导管','Acinar','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','2C','32C0F4','管腔','Acinar Lumen','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','2C','32C061','腺泡/导管细胞核','Acinar Epithelium Nucleus','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','2C','32C060','尿道及尿道周围','Urethral and Periurethral Area','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','2E','32E0FA','生精小管','Seminiferous Tubules','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','2E','32E0FB','生精小管内腔','Seminiferous Tubules Lumen','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','2E','32E0FC','生精细胞核','Spermatogenic Cell','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','2E','32E0FD','支持细胞核','Leydig Nucleus','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','2E','32E0FE','间质细胞核','Mesenchyme Cell','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','2E','32E111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','2F','32F0F5','输出小管/附睾管黏膜上皮','Efferent Ducts and Epididymal Ducts','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','2F','32F0F4','输出小管/附睾管管腔','Efferent Ducts and Epididymal Ducts Lumen','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','2F','32F0F7','管内精子','Sperm Area','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','2F','32F0F6','输出小管/附睾管黏膜上皮细胞核','Mucosal Epithelial Nucleus','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','2F','32F111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','69','36906D','腺泡','Acinus','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','69','36906E','腺泡上皮细胞核','Acinar Epithelial Cell','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','69','369111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','5F','35F101','晶状体','Crystalline Lens','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','5F','35F103','视网膜','Retina','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','5F','35F111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','5E','35E003','血管','Vessel','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','5E','35E111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','5D','35D113','空腔','Lumen','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','5D','35D111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','0E','30E111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','0E','30E035','黏膜上皮','Mucosal Epithelium','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','0E','30E133','腺泡','Gland','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','11','311111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','11','311035','黏膜上皮','Mucosal Epithelium','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','11','311036','黏膜上皮细胞核','Mucosal Epithelium Nucleus','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','12','312111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','12','312145','门管区','Portal Area','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','12','312146','中央静脉','Central Vein','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','12','312147','大静脉','Large Vein','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','12','312149','肝细胞核','Hepatocyte Nucleus','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','12','31214A','胆管','Bile Duct','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','12','31214D','窦内细胞核','Sinus Cell','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','09','309111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','09','30906F','导管','Ducts','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','09','30906E','腺泡细胞核','Acinar Cell','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','09','30906D','腺泡','Acinar','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','0D','30D111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','0D','30D114','复层扁平上皮','Stratified Squamous Epithelium','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','0D','30D01C','固有层+肌层','Lamina Propria and Muscularis','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','0A','30A111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','0A','30A06F','导管','Ducts','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','0A','30A06E','腺泡细胞核','Acinar Cell','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','0A','30A06D','腺泡','Acinar','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','0B','30B111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','0B','30B06F','导管','Ducts','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','0B','30B06E','腺泡细胞核','Acinar Cell','RO',1,3);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','0B','30B06D','腺泡','Acinar','RO',1,2);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','83','38301E','黏膜上皮＋固有层','Mucosa Epithelium and Lamina Propria Mucosa','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','83','38301F','黏膜上皮＋黏膜下层 ','Mucosal Muscular Layer and Submucosal','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','83','38300C','肌层','Muscular','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','83','383049','淋巴组织','Lymphatic Tissue','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','83','383111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','82','38201E','黏膜上皮＋固有层','Mucosa Epithelium and Lamina Propria Mucosa','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','82','38201F','黏膜肌层＋黏膜下层 ','Mucosal Muscular Layer and Submucosal','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','82','38200C','肌层','Muscular','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','82','382064','淋巴小结','Lymphatic Nodule','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','82','382049','淋巴组织','Lymphatic Tissue','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','82','382111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','0F','30F035','黏膜上皮','Stratum Corneum','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','0F','30F00C','肌层','Muscularis','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','0F','30F120','食管腔','Lumen','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','0F','30F13B','黏膜固有层+黏膜肌层+黏膜下层','Subepithelium','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','0F','30F111','组织轮廓','Tissue Area','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','10','31001E','黏膜上皮+固有层','Mucosa Epithelium and Lamina Propria Mucosa','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','10','31001F','黏膜肌层+黏膜下层','Mucosal Muscular Layer and Submucosal','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','10','31000C','肌层','Muscular','RO',1,1);
INSERT INTO tb_structure (species_id,organ_code,structure_id,name,name_en,type,organization_id,structure_size) VALUES ('3','10','310111','组织轮廓','Tissue Area','RO',1,1);

-- 结构标签初始化
INSERT INTO tb_structure_tag ( structure_tag_set_id, structure_tag_name, structure_id, organization_id, create_by, update_by ) SELECT
                                                                                                                                   b.structure_tag_set_id,
                                                                                                                                   CONCAT( c.NAME, b.structure_tag_set_name, a.`name` ),
                                                                                                                                   a.structure_id,
                                                                                                                                   a.organization_id,
                                                                                                                                   1,
                                                                                                                                   1
FROM
    tb_structure a
        LEFT JOIN tb_structure_tag_set b ON a.species_id = b.species_id
        AND a.organ_code = b.organ_code
        AND a.organization_id = b.organization_id
        LEFT JOIN tb_species c ON b.species_id = c.species_id
        AND b.organization_id = c.organization_id
WHERE
    a.species_id = '3';

-- 结构标签颜色
UPDATE tb_structure_tag SET rgb = 'rgb(255, 0, 0)',hex = '#FF0000' WHERE organization_id = 1 AND structure_id = '34C002';
UPDATE tb_structure_tag SET rgb = 'rgb(119, 172, 48)',hex = '#77AC30' WHERE organization_id = 1 AND structure_id = '34C003';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 128, 255)',hex = '#0080FF' WHERE organization_id = 1 AND structure_id = '34C004';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 255, 0)',hex = '#00FF00' WHERE organization_id = 1 AND structure_id = '34C006';
UPDATE tb_structure_tag SET rgb = 'rgb(77, 190, 238)',hex = '#4DBEEE' WHERE organization_id = 1 AND structure_id = '34C027';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 128, 128)',hex = '#FF8080' WHERE organization_id = 1 AND structure_id = '34C111';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 0, 255)',hex = '#0000FF' WHERE organization_id = 1 AND structure_id = '34D111';
UPDATE tb_structure_tag SET rgb = 'rgb(162, 20, 47)',hex = '#A2142F' WHERE organization_id = 1 AND structure_id = '34D036';
UPDATE tb_structure_tag SET rgb = 'rgb(128, 128, 255)',hex = '#8080FF' WHERE organization_id = 1 AND structure_id = '34D035';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 255, 0)',hex = '#FFFF00' WHERE organization_id = 1 AND structure_id = '350111';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 128, 0)',hex = '#008000' WHERE organization_id = 1 AND structure_id = '35000B';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 0, 128)',hex = '#FF0080' WHERE organization_id = 1 AND structure_id = '34E011';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 0, 255)',hex = '#FF00FF' WHERE organization_id = 1 AND structure_id = '34E01A';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 0, 128)',hex = '#000080' WHERE organization_id = 1 AND structure_id = '34E022';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 200, 200)',hex = '#FFC8C8' WHERE organization_id = 1 AND structure_id = '34E004';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 255, 255)',hex = '#00FFFF' WHERE organization_id = 1 AND structure_id = '34E012';
UPDATE tb_structure_tag SET rgb = 'rgb(128, 128, 0)',hex = '#808000' WHERE organization_id = 1 AND structure_id = '34E111';
UPDATE tb_structure_tag SET rgb = 'rgb(200, 255, 200)',hex = '#C8FFC8' WHERE organization_id = 1 AND structure_id = '35C111';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 114, 189)',hex = '#0072BD' WHERE organization_id = 1 AND structure_id = '35C027';
UPDATE tb_structure_tag SET rgb = 'rgb(128, 0, 128)',hex = '#800080' WHERE organization_id = 1 AND structure_id = '35C02A';
UPDATE tb_structure_tag SET rgb = 'rgb(200, 200, 255)',hex = '#C8C8FF' WHERE organization_id = 1 AND structure_id = '35C05A';
UPDATE tb_structure_tag SET rgb = 'rgb(217, 83, 25)',hex = '#D95319' WHERE organization_id = 1 AND structure_id = '31B03E';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 128, 128)',hex = '#008080' WHERE organization_id = 1 AND structure_id = '31B03D';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 255, 200)',hex = '#FFFFC8' WHERE organization_id = 1 AND structure_id = '31B02D';
UPDATE tb_structure_tag SET rgb = 'rgb(237, 177, 32)',hex = '#EDB120' WHERE organization_id = 1 AND structure_id = '31B026';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 128, 0)',hex = '#FF8000' WHERE organization_id = 1 AND structure_id = '31B031';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 200, 255)',hex = '#FFC8FF' WHERE organization_id = 1 AND structure_id = '31B02E';
UPDATE tb_structure_tag SET rgb = 'rgb(126, 47, 142)',hex = '#7E2F8E' WHERE organization_id = 1 AND structure_id = '31B02F';
UPDATE tb_structure_tag SET rgb = 'rgb(128, 0, 255)',hex = '#8000FF' WHERE organization_id = 1 AND structure_id = '31B111';
UPDATE tb_structure_tag SET rgb = 'rgb(200, 255, 255)',hex = '#C8FFFF' WHERE organization_id = 1 AND structure_id = '31E035';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 0, 0)',hex = '#FF0000' WHERE organization_id = 1 AND structure_id = '31E036';
UPDATE tb_structure_tag SET rgb = 'rgb(119, 172, 48)',hex = '#77AC30' WHERE organization_id = 1 AND structure_id = '31E003';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 128, 255)',hex = '#0080FF' WHERE organization_id = 1 AND structure_id = '31E111';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 255, 0)',hex = '#00FF00' WHERE organization_id = 1 AND structure_id = '34B054';
UPDATE tb_structure_tag SET rgb = 'rgb(77, 190, 238)',hex = '#4DBEEE' WHERE organization_id = 1 AND structure_id = '34B051';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 128, 128)',hex = '#FF8080' WHERE organization_id = 1 AND structure_id = '34B052';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 0, 255)',hex = '#0000FF' WHERE organization_id = 1 AND structure_id = '34B03E';
UPDATE tb_structure_tag SET rgb = 'rgb(162, 20, 47)',hex = '#A2142F' WHERE organization_id = 1 AND structure_id = '34B111';
UPDATE tb_structure_tag SET rgb = 'rgb(128, 128, 255)',hex = '#8080FF' WHERE organization_id = 1 AND structure_id = '34403D';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 255, 0)',hex = '#FFFF00' WHERE organization_id = 1 AND structure_id = '34403E';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 128, 0)',hex = '#008000' WHERE organization_id = 1 AND structure_id = '344004';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 0, 128)',hex = '#FF0080' WHERE organization_id = 1 AND structure_id = '344111';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 0, 255)',hex = '#FF00FF' WHERE organization_id = 1 AND structure_id = '345046';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 0, 128)',hex = '#000080' WHERE organization_id = 1 AND structure_id = '345047';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 200, 200)',hex = '#FFC8C8' WHERE organization_id = 1 AND structure_id = '345004';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 255, 255)',hex = '#00FFFF' WHERE organization_id = 1 AND structure_id = '345051';
UPDATE tb_structure_tag SET rgb = 'rgb(128, 128, 0)',hex = '#808000' WHERE organization_id = 1 AND structure_id = '345048';
UPDATE tb_structure_tag SET rgb = 'rgb(200, 255, 200)',hex = '#C8FFC8' WHERE organization_id = 1 AND structure_id = '34504A';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 114, 189)',hex = '#0072BD' WHERE organization_id = 1 AND structure_id = '34505B';
UPDATE tb_structure_tag SET rgb = 'rgb(128, 0, 128)',hex = '#800080' WHERE organization_id = 1 AND structure_id = '345111';
UPDATE tb_structure_tag SET rgb = 'rgb(200, 200, 255)',hex = '#C8C8FF' WHERE organization_id = 1 AND structure_id = '30607F';
UPDATE tb_structure_tag SET rgb = 'rgb(217, 83, 25)',hex = '#D95319' WHERE organization_id = 1 AND structure_id = '306081';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 128, 128)',hex = '#008080' WHERE organization_id = 1 AND structure_id = '306082';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 255, 200)',hex = '#FFFFC8' WHERE organization_id = 1 AND structure_id = '306083';
UPDATE tb_structure_tag SET rgb = 'rgb(237, 177, 32)',hex = '#EDB120' WHERE organization_id = 1 AND structure_id = '306084';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 128, 0)',hex = '#FF8000' WHERE organization_id = 1 AND structure_id = '306004';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 200, 255)',hex = '#FFC8FF' WHERE organization_id = 1 AND structure_id = '306111';
UPDATE tb_structure_tag SET rgb = 'rgb(126, 47, 142)',hex = '#7E2F8E' WHERE organization_id = 1 AND structure_id = '37F07C';
UPDATE tb_structure_tag SET rgb = 'rgb(128, 0, 255)',hex = '#8000FF' WHERE organization_id = 1 AND structure_id = '37F088';
UPDATE tb_structure_tag SET rgb = 'rgb(200, 255, 255)',hex = '#C8FFFF' WHERE organization_id = 1 AND structure_id = '37F08A';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 0, 0)',hex = '#FF0000' WHERE organization_id = 1 AND structure_id = '37F003';
UPDATE tb_structure_tag SET rgb = 'rgb(119, 172, 48)',hex = '#77AC30' WHERE organization_id = 1 AND structure_id = '37F004';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 128, 255)',hex = '#0080FF' WHERE organization_id = 1 AND structure_id = '37F089';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 255, 0)',hex = '#00FF00' WHERE organization_id = 1 AND structure_id = '37F08F';
UPDATE tb_structure_tag SET rgb = 'rgb(77, 190, 238)',hex = '#4DBEEE' WHERE organization_id = 1 AND structure_id = '37F08B';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 128, 128)',hex = '#FF8080' WHERE organization_id = 1 AND structure_id = '37F07D';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 0, 255)',hex = '#0000FF' WHERE organization_id = 1 AND structure_id = '37F092';
UPDATE tb_structure_tag SET rgb = 'rgb(162, 20, 47)',hex = '#A2142F' WHERE organization_id = 1 AND structure_id = '30103D';
UPDATE tb_structure_tag SET rgb = 'rgb(128, 128, 255)',hex = '#8080FF' WHERE organization_id = 1 AND structure_id = '301056';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 255, 0)',hex = '#FFFF00' WHERE organization_id = 1 AND structure_id = '301057';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 128, 0)',hex = '#008000' WHERE organization_id = 1 AND structure_id = '30103E';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 0, 128)',hex = '#FF0080' WHERE organization_id = 1 AND structure_id = '301068';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 0, 255)',hex = '#FF00FF' WHERE organization_id = 1 AND structure_id = '301004';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 0, 128)',hex = '#000080' WHERE organization_id = 1 AND structure_id = '301111';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 200, 200)',hex = '#FFC8C8' WHERE organization_id = 1 AND structure_id = '305075';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 255, 255)',hex = '#00FFFF' WHERE organization_id = 1 AND structure_id = '305076';
UPDATE tb_structure_tag SET rgb = 'rgb(128, 128, 0)',hex = '#808000' WHERE organization_id = 1 AND structure_id = '305077';
UPDATE tb_structure_tag SET rgb = 'rgb(200, 255, 200)',hex = '#C8FFC8' WHERE organization_id = 1 AND structure_id = '305078';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 114, 189)',hex = '#0072BD' WHERE organization_id = 1 AND structure_id = '305027';
UPDATE tb_structure_tag SET rgb = 'rgb(128, 0, 128)',hex = '#800080' WHERE organization_id = 1 AND structure_id = '30506F';
UPDATE tb_structure_tag SET rgb = 'rgb(200, 200, 255)',hex = '#C8C8FF' WHERE organization_id = 1 AND structure_id = '305003';
UPDATE tb_structure_tag SET rgb = 'rgb(217, 83, 25)',hex = '#D95319' WHERE organization_id = 1 AND structure_id = '305111';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 128, 128)',hex = '#008080' WHERE organization_id = 1 AND structure_id = '37A06C';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 255, 200)',hex = '#FFFFC8' WHERE organization_id = 1 AND structure_id = '37A061';
UPDATE tb_structure_tag SET rgb = 'rgb(237, 177, 32)',hex = '#EDB120' WHERE organization_id = 1 AND structure_id = '37A07A';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 128, 0)',hex = '#FF8000' WHERE organization_id = 1 AND structure_id = '37A111';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 200, 255)',hex = '#FFC8FF' WHERE organization_id = 1 AND structure_id = '37A096';
UPDATE tb_structure_tag SET rgb = 'rgb(126, 47, 142)',hex = '#7E2F8E' WHERE organization_id = 1 AND structure_id = '37A097';
UPDATE tb_structure_tag SET rgb = 'rgb(128, 0, 255)',hex = '#8000FF' WHERE organization_id = 1 AND structure_id = '37A098';
UPDATE tb_structure_tag SET rgb = 'rgb(200, 255, 255)',hex = '#C8FFFF' WHERE organization_id = 1 AND structure_id = '37A099';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 0, 0)',hex = '#FF0000' WHERE organization_id = 1 AND structure_id = '37A0C3';
UPDATE tb_structure_tag SET rgb = 'rgb(119, 172, 48)',hex = '#77AC30' WHERE organization_id = 1 AND structure_id = '33F0BB';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 128, 255)',hex = '#0080FF' WHERE organization_id = 1 AND structure_id = '33F0BA';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 255, 0)',hex = '#00FF00' WHERE organization_id = 1 AND structure_id = '33F111';
UPDATE tb_structure_tag SET rgb = 'rgb(77, 190, 238)',hex = '#4DBEEE' WHERE organization_id = 1 AND structure_id = '3400BB';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 128, 128)',hex = '#FF8080' WHERE organization_id = 1 AND structure_id = '3400BA';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 0, 255)',hex = '#0000FF' WHERE organization_id = 1 AND structure_id = '340111';
UPDATE tb_structure_tag SET rgb = 'rgb(162, 20, 47)',hex = '#A2142F' WHERE organization_id = 1 AND structure_id = '33209C';
UPDATE tb_structure_tag SET rgb = 'rgb(128, 128, 255)',hex = '#8080FF' WHERE organization_id = 1 AND structure_id = '332003';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 255, 0)',hex = '#FFFF00' WHERE organization_id = 1 AND structure_id = '332004';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 128, 0)',hex = '#008000' WHERE organization_id = 1 AND structure_id = '332111';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 0, 128)',hex = '#FF0080' WHERE organization_id = 1 AND structure_id = '33E0A5';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 0, 255)',hex = '#FF00FF' WHERE organization_id = 1 AND structure_id = '33E003';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 0, 128)',hex = '#000080' WHERE organization_id = 1 AND structure_id = '33E004';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 200, 200)',hex = '#FFC8C8' WHERE organization_id = 1 AND structure_id = '33E111';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 255, 255)',hex = '#00FFFF' WHERE organization_id = 1 AND structure_id = '3390B3';
UPDATE tb_structure_tag SET rgb = 'rgb(128, 128, 0)',hex = '#808000' WHERE organization_id = 1 AND structure_id = '3390B2';
UPDATE tb_structure_tag SET rgb = 'rgb(200, 255, 200)',hex = '#C8FFC8' WHERE organization_id = 1 AND structure_id = '3390B4';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 114, 189)',hex = '#0072BD' WHERE organization_id = 1 AND structure_id = '3390B5';
UPDATE tb_structure_tag SET rgb = 'rgb(128, 0, 128)',hex = '#800080' WHERE organization_id = 1 AND structure_id = '339004';
UPDATE tb_structure_tag SET rgb = 'rgb(200, 200, 255)',hex = '#C8C8FF' WHERE organization_id = 1 AND structure_id = '339111';
UPDATE tb_structure_tag SET rgb = 'rgb(217, 83, 25)',hex = '#D95319' WHERE organization_id = 1 AND structure_id = '33D003';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 128, 128)',hex = '#008080' WHERE organization_id = 1 AND structure_id = '33D004';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 255, 200)',hex = '#FFFFC8' WHERE organization_id = 1 AND structure_id = '33D111';
UPDATE tb_structure_tag SET rgb = 'rgb(237, 177, 32)',hex = '#EDB120' WHERE organization_id = 1 AND structure_id = '324004';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 128, 0)',hex = '#FF8000' WHERE organization_id = 1 AND structure_id = '3240CB';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 200, 255)',hex = '#FFC8FF' WHERE organization_id = 1 AND structure_id = '324003';
UPDATE tb_structure_tag SET rgb = 'rgb(126, 47, 142)',hex = '#7E2F8E' WHERE organization_id = 1 AND structure_id = '324111';
UPDATE tb_structure_tag SET rgb = 'rgb(128, 0, 255)',hex = '#8000FF' WHERE organization_id = 1 AND structure_id = '32C111';
UPDATE tb_structure_tag SET rgb = 'rgb(200, 255, 255)',hex = '#C8FFFF' WHERE organization_id = 1 AND structure_id = '32C06C';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 0, 0)',hex = '#FF0000' WHERE organization_id = 1 AND structure_id = '32C0F4';
UPDATE tb_structure_tag SET rgb = 'rgb(119, 172, 48)',hex = '#77AC30' WHERE organization_id = 1 AND structure_id = '32C061';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 128, 255)',hex = '#0080FF' WHERE organization_id = 1 AND structure_id = '32C060';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 255, 0)',hex = '#00FF00' WHERE organization_id = 1 AND structure_id = '32E0FA';
UPDATE tb_structure_tag SET rgb = 'rgb(77, 190, 238)',hex = '#4DBEEE' WHERE organization_id = 1 AND structure_id = '32E0FB';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 128, 128)',hex = '#FF8080' WHERE organization_id = 1 AND structure_id = '32E0FC';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 0, 255)',hex = '#0000FF' WHERE organization_id = 1 AND structure_id = '32E0FD';
UPDATE tb_structure_tag SET rgb = 'rgb(162, 20, 47)',hex = '#A2142F' WHERE organization_id = 1 AND structure_id = '32E0FE';
UPDATE tb_structure_tag SET rgb = 'rgb(128, 128, 255)',hex = '#8080FF' WHERE organization_id = 1 AND structure_id = '32E111';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 255, 0)',hex = '#FFFF00' WHERE organization_id = 1 AND structure_id = '32F0F5';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 128, 0)',hex = '#008000' WHERE organization_id = 1 AND structure_id = '32F0F4';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 0, 128)',hex = '#FF0080' WHERE organization_id = 1 AND structure_id = '32F0F7';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 0, 255)',hex = '#FF00FF' WHERE organization_id = 1 AND structure_id = '32F0F6';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 0, 128)',hex = '#000080' WHERE organization_id = 1 AND structure_id = '32F111';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 200, 200)',hex = '#FFC8C8' WHERE organization_id = 1 AND structure_id = '36906D';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 255, 255)',hex = '#00FFFF' WHERE organization_id = 1 AND structure_id = '36906E';
UPDATE tb_structure_tag SET rgb = 'rgb(128, 128, 0)',hex = '#808000' WHERE organization_id = 1 AND structure_id = '369111';
UPDATE tb_structure_tag SET rgb = 'rgb(200, 255, 200)',hex = '#C8FFC8' WHERE organization_id = 1 AND structure_id = '35F101';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 114, 189)',hex = '#0072BD' WHERE organization_id = 1 AND structure_id = '35F103';
UPDATE tb_structure_tag SET rgb = 'rgb(128, 0, 128)',hex = '#800080' WHERE organization_id = 1 AND structure_id = '35F111';
UPDATE tb_structure_tag SET rgb = 'rgb(200, 200, 255)',hex = '#C8C8FF' WHERE organization_id = 1 AND structure_id = '35E003';
UPDATE tb_structure_tag SET rgb = 'rgb(217, 83, 25)',hex = '#D95319' WHERE organization_id = 1 AND structure_id = '35E111';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 128, 128)',hex = '#008080' WHERE organization_id = 1 AND structure_id = '35D113';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 255, 200)',hex = '#FFFFC8' WHERE organization_id = 1 AND structure_id = '35D111';
UPDATE tb_structure_tag SET rgb = 'rgb(237, 177, 32)',hex = '#EDB120' WHERE organization_id = 1 AND structure_id = '30E111';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 128, 0)',hex = '#FF8000' WHERE organization_id = 1 AND structure_id = '30E035';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 200, 255)',hex = '#FFC8FF' WHERE organization_id = 1 AND structure_id = '30E133';
UPDATE tb_structure_tag SET rgb = 'rgb(126, 47, 142)',hex = '#7E2F8E' WHERE organization_id = 1 AND structure_id = '311111';
UPDATE tb_structure_tag SET rgb = 'rgb(128, 0, 255)',hex = '#8000FF' WHERE organization_id = 1 AND structure_id = '311035';
UPDATE tb_structure_tag SET rgb = 'rgb(200, 255, 255)',hex = '#C8FFFF' WHERE organization_id = 1 AND structure_id = '311036';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 0, 0)',hex = '#FF0000' WHERE organization_id = 1 AND structure_id = '312111';
UPDATE tb_structure_tag SET rgb = 'rgb(119, 172, 48)',hex = '#77AC30' WHERE organization_id = 1 AND structure_id = '312145';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 128, 255)',hex = '#0080FF' WHERE organization_id = 1 AND structure_id = '312146';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 255, 0)',hex = '#00FF00' WHERE organization_id = 1 AND structure_id = '312147';
UPDATE tb_structure_tag SET rgb = 'rgb(77, 190, 238)',hex = '#4DBEEE' WHERE organization_id = 1 AND structure_id = '312149';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 128, 128)',hex = '#FF8080' WHERE organization_id = 1 AND structure_id = '31214A';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 0, 255)',hex = '#0000FF' WHERE organization_id = 1 AND structure_id = '31214D';
UPDATE tb_structure_tag SET rgb = 'rgb(162, 20, 47)',hex = '#A2142F' WHERE organization_id = 1 AND structure_id = '309111';
UPDATE tb_structure_tag SET rgb = 'rgb(128, 128, 255)',hex = '#8080FF' WHERE organization_id = 1 AND structure_id = '30906F';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 255, 0)',hex = '#FFFF00' WHERE organization_id = 1 AND structure_id = '30906E';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 128, 0)',hex = '#008000' WHERE organization_id = 1 AND structure_id = '30906D';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 0, 128)',hex = '#FF0080' WHERE organization_id = 1 AND structure_id = '30D111';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 0, 255)',hex = '#FF00FF' WHERE organization_id = 1 AND structure_id = '30D114';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 0, 128)',hex = '#000080' WHERE organization_id = 1 AND structure_id = '30D01C';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 200, 200)',hex = '#FFC8C8' WHERE organization_id = 1 AND structure_id = '30A111';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 255, 255)',hex = '#00FFFF' WHERE organization_id = 1 AND structure_id = '30A06F';
UPDATE tb_structure_tag SET rgb = 'rgb(128, 128, 0)',hex = '#808000' WHERE organization_id = 1 AND structure_id = '30A06E';
UPDATE tb_structure_tag SET rgb = 'rgb(200, 255, 200)',hex = '#C8FFC8' WHERE organization_id = 1 AND structure_id = '30A06D';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 114, 189)',hex = '#0072BD' WHERE organization_id = 1 AND structure_id = '30B111';
UPDATE tb_structure_tag SET rgb = 'rgb(128, 0, 128)',hex = '#800080' WHERE organization_id = 1 AND structure_id = '30B06F';
UPDATE tb_structure_tag SET rgb = 'rgb(200, 200, 255)',hex = '#C8C8FF' WHERE organization_id = 1 AND structure_id = '30B06E';
UPDATE tb_structure_tag SET rgb = 'rgb(217, 83, 25)',hex = '#D95319' WHERE organization_id = 1 AND structure_id = '30B06D';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 128, 128)',hex = '#008080' WHERE organization_id = 1 AND structure_id = '38301E';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 255, 200)',hex = '#FFFFC8' WHERE organization_id = 1 AND structure_id = '38301F';
UPDATE tb_structure_tag SET rgb = 'rgb(237, 177, 32)',hex = '#EDB120' WHERE organization_id = 1 AND structure_id = '38300C';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 128, 0)',hex = '#FF8000' WHERE organization_id = 1 AND structure_id = '383049';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 200, 255)',hex = '#FFC8FF' WHERE organization_id = 1 AND structure_id = '383111';
UPDATE tb_structure_tag SET rgb = 'rgb(126, 47, 142)',hex = '#7E2F8E' WHERE organization_id = 1 AND structure_id = '38201E';
UPDATE tb_structure_tag SET rgb = 'rgb(128, 0, 255)',hex = '#8000FF' WHERE organization_id = 1 AND structure_id = '38201F';
UPDATE tb_structure_tag SET rgb = 'rgb(200, 255, 255)',hex = '#C8FFFF' WHERE organization_id = 1 AND structure_id = '38200C';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 0, 0)',hex = '#FF0000' WHERE organization_id = 1 AND structure_id = '382064';
UPDATE tb_structure_tag SET rgb = 'rgb(119, 172, 48)',hex = '#77AC30' WHERE organization_id = 1 AND structure_id = '382049';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 128, 255)',hex = '#0080FF' WHERE organization_id = 1 AND structure_id = '382111';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 255, 0)',hex = '#00FF00' WHERE organization_id = 1 AND structure_id = '30F035';
UPDATE tb_structure_tag SET rgb = 'rgb(77, 190, 238)',hex = '#4DBEEE' WHERE organization_id = 1 AND structure_id = '30F00C';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 128, 128)',hex = '#FF8080' WHERE organization_id = 1 AND structure_id = '30F120';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 0, 255)',hex = '#0000FF' WHERE organization_id = 1 AND structure_id = '30F13B';
UPDATE tb_structure_tag SET rgb = 'rgb(162, 20, 47)',hex = '#A2142F' WHERE organization_id = 1 AND structure_id = '30F111';
UPDATE tb_structure_tag SET rgb = 'rgb(128, 128, 255)',hex = '#8080FF' WHERE organization_id = 1 AND structure_id = '31001E';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 255, 0)',hex = '#FFFF00' WHERE organization_id = 1 AND structure_id = '31001F';
UPDATE tb_structure_tag SET rgb = 'rgb(0, 128, 0)',hex = '#008000' WHERE organization_id = 1 AND structure_id = '31000C';
UPDATE tb_structure_tag SET rgb = 'rgb(255, 0, 128)',hex = '#FF0080' WHERE organization_id = 1 AND structure_id = '310111';

